version: '3.0'

expectations:
  population_size: 1000

actions:
  
  generate_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-format=feather
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity.feather

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  generate_rates_1:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_rates --index-date-range "2015-01-01 to 2018-12-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inpu*.feather
  
  generate_rates_2:    
    run: cohortextractor:latest generate_cohort --study-definition study_definition_rates --index-date-range "2019-01-01 to 2022-12-01 by month" --skip-existing --output-dir=output --output-format=feather
    outputs:      
      highly_sensitive:
        cohort: output/measures/inp*.feather

  join_ethnicity:
    run: python:latest python analysis/join_ethnicity.py
    needs:
      [
        generate_rates_1,
        generate_rates_2,
        generate_ethnicity,
      ]
    outputs:
      highly_sensitive:
        cohort: output/measures/in*.feather
  
  generate_measures:
    run: cohortextractor:latest generate_measures --study-definition study_definition_rates --skip-existing --output-dir=output/measures
    needs: 
      [
        generate_rates_1,
        generate_rates_2,
        join_ethnicity,
      ]
    outputs:
      moderately_sensitive:
        measure_csv1: output/measures/measure_self_harmAE*_rate.csv
        measure_csv5: output/measures/measure_self_harmAEbyRegion*_rate.csv
        measure_csv6: output/measures/measure_self_harmAEbyIMD*_rate.csv
        measure_csv7: output/measures/measure_self_harmAEbyEthnicity*_rate.csv
        measure_csv8: output/measures/measure_self_harmAEbyAge*_rate.csv

  # describe_trends:
  #   run: r:latest analysis/Descriptive_trends.R
  #   needs: 
  #     [
  #       generate_measures_ADT,
  #       generate_study_population
  #     ]
  #   outputs:
  #     moderately_sensitive:
  #       fig1: output/ADT_inj_rat.png
  #       fig2: output/ADT_inj1_ra.png
  #       fig3: output/ADT_inj3_ra.png
  #       fig4: output/ADT_inj6_ra.png
  #       fig5: output/ADTinjbyReg.png
  #       fig6: output/ADTinjbyIMD.png
  #       fig7: output/ADTinjbyEth.png
  #       fig8: output/ADTinjbyAge.png
  #       fig9: output/ADT_oral_ra.png
  #       fig10: output/ADToralbyRe.png
  #       fig11: output/ADToralbyIM.png
  #       fig12: output/ADToralbyEt.png
  #       fig13: output/ADToralbyAg.png
  #       fig14: output/ADTsecongen.png        
  #       csv1: output/ADT_inj_rat_rounded.csv
  #       csv2: output/ADT_inj1_ra_rounded.csv
  #       csv3: output/ADT_inj3_ra_rounded.csv
  #       csv4: output/ADT_inj6_ra_rounded.csv
  #       csv5: output/ADTinjbyReg_rounded.csv
  #       csv6: output/ADTinjbyIMD_rounded.csv
  #       csv7: output/ADTinjbyEth_rounded.csv
  #       csv8: output/ADTinjbyAge_rounded.csv
  #       csv9: output/ADT_oral_ra_rounded.csv
  #       csv10: output/ADToralbyRe_rounded.csv
  #       csv11: output/ADToralbyIM_rounded.csv
  #       csv12: output/ADToralbyEt_rounded.csv
  #       csv13: output/ADToralbyAg_rounded.csv
  #       csv14: output/ADTsecongen_rounded.csv
  #       csv15: output/Table1.csv

